package it.unibs.dii.pajc.pig.client.view.component;

import it.unibs.dii.pajc.pig.client.utility.UtilityConstant;

import javax.imageio.ImageIO;
import javax.swing.*;
import java.awt.*;
import java.awt.image.BufferedImage;
import java.io.IOException;
import java.net.URL;
import java.util.ArrayList;

public class PIGForm extends JFrame {

    private static final String PRE_TITLE_FORM = "Project IoT Greenhouse - ";

    public PIGForm() throws HeadlessException {
        this(null);
    }

    public PIGForm(String title) throws HeadlessException {
        super();
        setTitle(title);
        initComponent();
    }

    private void initComponent() {
        try {
            URL iconURl = getClass().getResource(UtilityConstant.RESOURCES_LOGO);
            BufferedImage image = ImageIO.read(iconURl);
            ArrayList<Image> icons = new ArrayList<>();

            icons.add(image.getScaledInstance(UtilityConstant.ICON_DIMENSION_16, UtilityConstant.ICON_DIMENSION_16, Image.SCALE_SMOOTH));
            icons.add(image.getScaledInstance(UtilityConstant.ICON_DIMENSION_32, UtilityConstant.ICON_DIMENSION_32, Image.SCALE_SMOOTH));
            icons.add(image.getScaledInstance(UtilityConstant.ICON_DIMENSION_48, UtilityConstant.ICON_DIMENSION_48, Image.SCALE_SMOOTH));
            icons.add(image.getScaledInstance(UtilityConstant.ICON_DIMENSION_64, UtilityConstant.ICON_DIMENSION_64, Image.SCALE_SMOOTH));
            icons.add(image.getScaledInstance(UtilityConstant.ICON_DIMENSION_128, UtilityConstant.ICON_DIMENSION_128, Image.SCALE_SMOOTH));
            icons.add(image.getScaledInstance(UtilityConstant.ICON_DIMENSION_256, UtilityConstant.ICON_DIMENSION_256, Image.SCALE_SMOOTH));
            icons.add(image);

            this.setIconImages(icons);
        } catch (IOException e) {
            e.printStackTrace();
        }

    }

    @Override
    public void setTitle(String title) {
        setTitle(title, false);
    }

    public void setTitle(String title, boolean noPreTitle) {
        if (!noPreTitle)
            title = PRE_TITLE_FORM + title;
        super.setTitle(title);
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new BorderLayout(0, 0));
    }
}
