package it.unibs.dii.pajc.pig.client.view.component;

import it.unibs.dii.pajc.pig.client.utility.UtilityConstant;

import javax.imageio.ImageIO;
import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.image.BufferedImage;
import java.io.IOException;
import java.net.URL;
import java.util.ArrayList;

public class PIGForm extends JFrame {

    private static final String PRE_TITLE_FORM = "Project IoT Greenhouse - ";

    private JPanel panel1; //USELESS
    private PIGBackgroundPanel backgroundPanel;

    public PIGForm() throws HeadlessException {
        this(null);
    }

    public PIGForm(String title) throws HeadlessException {
        super();
        $$$setupUI$$$();
        setTitle(title);
        initComponent();
    }

    private void initComponent() {
        /***** ICON SETUP ******/
        try {
            URL iconURl = getClass().getResource(UtilityConstant.RESOURCES_LOGO);
            BufferedImage image = ImageIO.read(iconURl);
            ArrayList<Image> icons = new ArrayList<>();

            icons.add(image.getScaledInstance(UtilityConstant.ICON_DIMENSION_16, UtilityConstant.ICON_DIMENSION_16, Image.SCALE_SMOOTH));
            icons.add(image.getScaledInstance(UtilityConstant.ICON_DIMENSION_32, UtilityConstant.ICON_DIMENSION_32, Image.SCALE_SMOOTH));
            icons.add(image.getScaledInstance(UtilityConstant.ICON_DIMENSION_48, UtilityConstant.ICON_DIMENSION_48, Image.SCALE_SMOOTH));
            icons.add(image.getScaledInstance(UtilityConstant.ICON_DIMENSION_64, UtilityConstant.ICON_DIMENSION_64, Image.SCALE_SMOOTH));
            icons.add(image.getScaledInstance(UtilityConstant.ICON_DIMENSION_128, UtilityConstant.ICON_DIMENSION_128, Image.SCALE_SMOOTH));
            icons.add(image.getScaledInstance(UtilityConstant.ICON_DIMENSION_256, UtilityConstant.ICON_DIMENSION_256, Image.SCALE_SMOOTH));
            icons.add(image);

            this.setIconImages(icons);
        } catch (IOException e) {
            e.printStackTrace();
        }

        /***** FRAME SETUP ******/
        super.setContentPane(backgroundPanel);
    }

    public void setGenericToolBarVisible(boolean visible) {
        backgroundPanel.setGenericToolBarVisible(visible);
    }

    public boolean isGenericToolBarVisible() {
        return backgroundPanel.isGenericToolBarVisible();
    }

    public void setHelpButtonVisible(boolean visible) {
        backgroundPanel.setHelpButtonVisible(visible);
    }

    public boolean isHelpButtonVisible() {
        return backgroundPanel.isHelpButtonVisible();
    }

    @Override
    public void setContentPane(Container contentPane) {
        BorderLayout layout = (BorderLayout) backgroundPanel.getLayout();
        Component content = layout.getLayoutComponent(BorderLayout.CENTER);
        if (content != null)
            backgroundPanel.remove(content);
        backgroundPanel.add(contentPane, BorderLayout.CENTER);
    }

    @Override
    public void setTitle(String title) {
        setTitle(title, false);
    }

    public void setTitle(String title, boolean noPreTitle) {
        if (!noPreTitle)
            title = PRE_TITLE_FORM + title;
        super.setTitle(title);
    }

    public void addHelpActionListener(ActionListener listener) {
        backgroundPanel.addHelpActionListener(listener);
    }

    public void removeHelpActionListener(ActionListener listener) {
        backgroundPanel.removeHelpActionListener(listener);
    }

    public void fireHelpActionListener(ActionEvent evt) {
        backgroundPanel.fireHelpActionListener(evt);
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panel1 = new JPanel();
        panel1.setLayout(new BorderLayout(0, 0));
        backgroundPanel = new PIGBackgroundPanel();
        backgroundPanel.setLayout(new BorderLayout(0, 0));
        panel1.add(backgroundPanel, BorderLayout.CENTER);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panel1;
    }
}
