package it.unibs.dii.pajc.pig.client.view.component;

import javax.imageio.ImageIO;
import javax.swing.*;
import java.awt.*;
import java.awt.image.BufferedImage;
import java.io.IOException;
import java.net.URL;
import java.util.ArrayList;

public class PIGForm extends JFrame {

    public static final String RESOURCES_LOGO = "/images/logo.png";
    public static final int ICON_DIMENSION_16 = 16;
    public static final int ICON_DIMENSION_32 = 32;
    public static final int ICON_DIMENSION_48 = 48;
    public static final int ICON_DIMENSION_64 = 64;
    public static final int ICON_DIMENSION_128 = 128;
    public static final int ICON_DIMENSION_256 = 256;

    private static final String PRE_TITLE_FORM = "Project IoT Greenhouse - ";

    public PIGForm() throws HeadlessException {
        this(null);
    }

    public PIGForm(String title) throws HeadlessException {
        super();
        setTitle(title);
        initComponent();
    }

    private void initComponent() {
        try {
            URL iconURl = getClass().getResource(RESOURCES_LOGO);
            BufferedImage image = ImageIO.read(iconURl);
            ArrayList<Image> icons = new ArrayList<>();

            icons.add(image.getScaledInstance(ICON_DIMENSION_16, ICON_DIMENSION_16, Image.SCALE_SMOOTH));
            icons.add(image.getScaledInstance(ICON_DIMENSION_32, ICON_DIMENSION_32, Image.SCALE_SMOOTH));
            icons.add(image.getScaledInstance(ICON_DIMENSION_48, ICON_DIMENSION_48, Image.SCALE_SMOOTH));
            icons.add(image.getScaledInstance(ICON_DIMENSION_64, ICON_DIMENSION_64, Image.SCALE_SMOOTH));
            icons.add(image.getScaledInstance(ICON_DIMENSION_128, ICON_DIMENSION_128, Image.SCALE_SMOOTH));
            icons.add(image.getScaledInstance(ICON_DIMENSION_256, ICON_DIMENSION_256, Image.SCALE_SMOOTH));
            icons.add(image);

            this.setIconImages(icons);
        } catch (IOException e) {
            e.printStackTrace();
        }

    }

    @Override
    public void setTitle(String title) {
        setTitle(title, false);
    }

    public void setTitle(String title, boolean noPreTitle) {
        if (!noPreTitle)
            title = PRE_TITLE_FORM + title;
        super.setTitle(title);
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new BorderLayout(0, 0));
    }
}
