package it.unibs.dii.pajc.pig.client.view;


import javax.swing.*;
import java.awt.*;
import java.util.ResourceBundle;

public class ConnectionForm {
    private JPanel backgroundPanel;

    private static ResourceBundle localizationBundle = ResourceBundle.getBundle("ConnectionForm");

    public static void main(String[] args) {
        JFrame frame = new JFrame(localizationBundle.getString("title"));
        frame.setContentPane(new ConnectionForm().backgroundPanel);
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.pack();
        frame.setVisible(true);
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        backgroundPanel = new JPanel();
        backgroundPanel.setLayout(new BorderLayout(0, 0));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return backgroundPanel;
    }

    private void createUIComponents() {
        // TODO: place custom component creation code here
    }
}
